/**
 * Protein-Engine web entry point.
 *
 * Loads the pe-wasm module, runs a demo scoring call, and renders results.
 * The WASM pkg/ directory is produced by `wasm-pack build crates/pe-wasm`.
 */

import type { FitnessScore } from "./types";

const statusEl = document.getElementById("status")!;
const outputEl = document.getElementById("output")!;

function setStatus(msg: string, error = false): void {
  statusEl.textContent = msg;
  statusEl.className = error ? "error" : "status";
}

function appendOutput(label: string, data: unknown): void {
  outputEl.textContent += `── ${label} ${"─".repeat(Math.max(0, 50 - label.length))}\n`;
  outputEl.textContent += JSON.stringify(data, null, 2) + "\n\n";
}

async function main(): Promise<void> {
  try {
    // Dynamic import — pkg/ is generated by wasm-pack build
    const wasm = await import("pe-wasm");

    setStatus("WASM module loaded. Running demo…");

    // Score a hardcoded OCT4 fragment
    const demoSequence = "MAGHLASDFAFSPPPGGGGDGPGGPEPGWVD";
    const score: FitnessScore = wasm.score_sequence(demoSequence);
    appendOutput("score_sequence", { sequence: demoSequence, score });

    // Search for similar sequences (will be empty until RVF loaded)
    const similar = wasm.search_similar(demoSequence, 5);
    appendOutput("search_similar", similar);

    // Verify the (empty) ledger
    const ledgerStatus = wasm.verify_ledger();
    appendOutput("verify_ledger", ledgerStatus);

    setStatus("Demo complete.");

    // TODO: Add file input for .rvf upload
    // const fileInput = document.createElement("input");
    // fileInput.type = "file";
    // fileInput.accept = ".rvf";
    // fileInput.addEventListener("change", async (e) => {
    //   const file = (e.target as HTMLInputElement).files?.[0];
    //   if (!file) return;
    //   const buffer = new Uint8Array(await file.arrayBuffer());
    //   const loadResult = wasm.load_rvf(buffer);
    //   appendOutput("load_rvf", loadResult);
    // });
    // document.body.appendChild(fileInput);
  } catch (err) {
    setStatus(`Failed to load WASM module: ${err}`, true);
    console.error(err);
  }
}

main();
