/**
 * Type declarations for the pe-wasm WASM module.
 *
 * Generated by wasm-pack in ../pkg/. This stub allows TypeScript to
 * compile before the WASM package is built.
 */
declare module "pe-wasm" {
  /** Score an amino acid sequence. Returns fitness components. */
  export function score_sequence(sequence: string): {
    reprogramming_efficiency: number;
    expression_stability: number;
    structural_plausibility: number;
    safety_score: number;
    composite: number;
  };

  /** Run one evolution cycle on a population. */
  export function run_evolution_step(
    population_json: string,
    config_json: string,
  ): {
    generation: number;
    variants_created: number;
    variants_scored: number;
    promoted: Array<{ name: string; sequence: string; composite: number }>;
  };

  /** Run a local quantum VQE simulation. */
  export function run_local_quantum_sim(hamiltonian_json: string): {
    ground_state_energy: number;
    optimal_parameters: number[];
    converged: boolean;
    iterations: number;
  };

  /** Search for sequences similar to the query. */
  export function search_similar(
    sequence: string,
    k: number,
  ): Array<{ id: string; similarity: number }>;

  /** Verify the integrity of the ledger chain. */
  export function verify_ledger(): { valid: boolean };

  /** Load an RVF file into the WASM engine. */
  export function load_rvf(data: Uint8Array): {
    vectors_loaded: number;
    journal_entries: number;
  };
}
